jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3.3.0
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3.9.0
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Cache SonarCloud packages
      uses: actions/cache@v3.2.3
      with:
        key: ${{ runner.os }}-sonar
        path: ~/.sonar/cache
        restore-keys: ${{ runner.os }}-sonar
    - continue-on-error: true
      name: Cache Gradle
      uses: actions/cache@v3.2.3
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')
          }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Build and analyze
      run: ./gradlew clean build
    - continue-on-error: true
      name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Click here to download
        path: jar/build/libs/TAB-**.jar
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
